const fr: Record<string, string> = {
  "Dashboard":"Tableau de bord","Curriculum":"Programme scolaire","Search":"Rechercher","Install App":"Installer l'application","New Lesson Plan":"Nouveau plan de leçon",
  "Toggle language":"Changer de langue","Toggle theme":"Changer de thème","Switch to French":"Passer en français","Switch to light theme":"Passer au thème clair","Switch to dark theme":"Passer au thème sombre",
  "Account security":"Sécurité du compte","Account Security":"Sécurité du compte","Logout":"Se déconnecter","KCS Lesson Planner":"Planificateur de leçons KCS","A4 print-ready":"Prêt pour l'impression A4",
  "Profile Photo":"Photo de profil","Choose photo":"Choisir une photo","Remove photo":"Supprimer la photo","Change Password":"Modifier le mot de passe","Change Email":"Modifier l'adresse e-mail",
  "Current password":"Mot de passe actuel","New password":"Nouveau mot de passe","Confirm password":"Confirmer le mot de passe","New email":"Nouvelle adresse e-mail","Show password":"Afficher le mot de passe","Hide password":"Masquer le mot de passe",
  "Save":"Enregistrer","Cancel":"Annuler","Close":"Fermer","Password updated":"Mot de passe mis à jour","Password updated successfully.":"Mot de passe mis à jour avec succès.",
  "The new password confirmation does not match.":"La confirmation du nouveau mot de passe ne correspond pas.","Unable to update password.":"Impossible de mettre à jour le mot de passe.",
  "Email change requested. Please sign in again.":"Modification de l'adresse e-mail demandée. Veuillez vous reconnecter.","Unable to update email.":"Impossible de mettre à jour l'adresse e-mail.",
  "After changing email, you may need to confirm the new address depending on Supabase email settings. You will be signed out for security.":"Après la modification, vous devrez peut-être confirmer la nouvelle adresse selon les paramètres e-mail de Supabase. Vous serez déconnecté par sécurité.",
  "Access Portal":"Portail d'accès","Sign in":"Se connecter","Create account":"Créer un compte","Password":"Mot de passe","Email":"Adresse e-mail","Full name":"Nom complet","Loading secure session...":"Chargement de la session sécurisée...",
  "Select department":"Sélectionner un département","Recover":"Récupérer","Password Recovery Center":"Centre de récupération du mot de passe","Temporary password":"Mot de passe temporaire","Optional temporary password":"Mot de passe temporaire facultatif","Set temporary password":"Définir un mot de passe temporaire",
  "Account activated":"Compte activé","Account disabled":"Compte désactivé","Active":"Actif","Inactive":"Inactif","Active users":"Utilisateurs actifs","Inactive users":"Utilisateurs inactifs",
  "User Administration":"Administration des utilisateurs","Users & Roles":"Utilisateurs et rôles","Search users":"Rechercher des utilisateurs","Any role":"Tous les rôles","Any user status":"Tous les statuts utilisateur","Any department":"Tous les départements","Any course":"Tous les cours","Any class":"Toutes les classes","Any lesson activity":"Toute activité de leçon",
  "Has lesson plans":"Possède des plans de leçon","No lesson plans":"Aucun plan de leçon","Has drafts":"Possède des brouillons","Has submitted plans":"Possède des plans soumis","Under review":"En cours de révision","Approved/final/published":"Approuvé/final/publié","Rejected/revision requested":"Rejeté/révision demandée",
  "Clear filters":"Effacer les filtres","Department":"Département","Subjects":"Matières","Grade classes":"Classes et niveaux","Save profile":"Enregistrer le profil","Edit":"Modifier","Delete":"Supprimer","No users match this search.":"Aucun utilisateur ne correspond à cette recherche.",
  "Recent Activity":"Activité récente","Upcoming Teaching Schedule":"Programme d'enseignement à venir","Completion Progress":"Progression de l'achèvement","Quick Actions":"Actions rapides","Curriculum Progress":"Progression du programme","Review Activity":"Activité de révision","Teachers Pending Submission":"Enseignants en attente de soumission","Department Shortcuts":"Raccourcis du département","Department Performance":"Performance des départements","Approval Statistics":"Statistiques d'approbation","Teacher Activity":"Activité des enseignants","Inspection Readiness":"Préparation à l'inspection","Data Overview":"Aperçu des données","Administrator Authority":"Pouvoirs de l'administrateur","System Activity":"Activité du système","Configuration Shortcuts":"Raccourcis de configuration",
  "No activity yet.":"Aucune activité pour le moment.","No upcoming lessons scheduled.":"Aucune leçon à venir n'est planifiée.","No department data yet.":"Aucune donnée de département pour le moment.",
  "Lesson Plans":"Plans de leçon","Search, filter, review, archive, restore, duplicate, and back up your local library.":"Recherchez, filtrez, révisez, archivez, restaurez, dupliquez et sauvegardez votre bibliothèque locale.",
  "Keywords":"Mots-clés","Teacher":"Enseignant","Subject":"Matière","Grade":"Niveau","Exact Date":"Date exacte","From Date":"Date de début","To Date":"Date de fin","Term":"Trimestre","Any week":"Toute semaine","Any month":"Tout mois","Any year":"Toute année","Topic":"Sujet","Tags":"Étiquettes","All":"Tous","Deleted":"Supprimé","Duplicate":"Dupliquer","Submit":"Soumettre","Review":"Réviser","HOD Approve":"Approbation du chef de département","Request Revision":"Demander une révision","Reject":"Rejeter","Final Approve":"Approbation finale","Publish":"Publier","Archive":"Archiver","Unarchive":"Désarchiver","Restore":"Restaurer",
  "No plans match the current filters.":"Aucun plan ne correspond aux filtres actuels.","Optional teacher":"Enseignant facultatif","Optional subject":"Matière facultative","Optional grade":"Niveau facultatif","Lesson plan duplicated":"Plan de leçon dupliqué","Lesson plan restored":"Plan de leçon restauré","A reviewer comment is required":"Un commentaire du réviseur est requis",
  "Curriculum Manager":"Gestionnaire du programme scolaire","Academic Year":"Année scolaire","Any term":"Tout trimestre","Any grade":"Tout niveau","Any subject":"Toute matière","Unit":"Unité","Subtopic":"Sous-thème","Competencies":"Compétences","Learning Objectives":"Objectifs d'apprentissage","Learning Outcomes":"Résultats d'apprentissage","References":"Références","Skills":"Compétences pratiques","Curriculum Standards":"Normes du programme","Export JSON":"Exporter en JSON","New Item":"Nouvel élément","Open":"Ouvrir","Save Curriculum Item":"Enregistrer l'élément du programme","No curriculum items match the filters.":"Aucun élément du programme ne correspond aux filtres.","Curriculum item saved":"Élément du programme enregistré","Curriculum item deleted":"Élément du programme supprimé","Curriculum JSON imported":"Programme JSON importé",
  "Everyone":"Tout le monde","Role":"Rôle","User":"Utilisateur","Choose target":"Choisir le destinataire","Message":"Message","Send":"Envoyer","Search messages":"Rechercher des messages","Any sender":"Tout expéditeur","Any audience":"Tout public","Read and unread":"Lus et non lus","Unread only":"Non lus uniquement","Read only":"Lus uniquement","From":"Du","To":"Au","New":"Nouveau","Edit message":"Modifier le message","Delete message":"Supprimer le message","Select message":"Sélectionner le message","No messages match this search.":"Aucun message ne correspond à cette recherche.","Message sent":"Message envoyé","Message updated":"Message mis à jour","Message deleted":"Message supprimé","Unable to load messages.":"Impossible de charger les messages.","Unable to send message.":"Impossible d'envoyer le message.","Unable to update message.":"Impossible de mettre à jour le message.","Unable to delete message.":"Impossible de supprimer le message.",
  "Access restricted":"Accès restreint","You do not have permission to view this lesson plan.":"Vous n'avez pas l'autorisation de consulter ce plan de leçon.","Switch to an authorized role or return to the visible lesson plan library.":"Passez à un rôle autorisé ou revenez à la bibliothèque de plans visible.","Back to plans":"Retour aux plans","Split daily":"Diviser en plans quotidiens","Build weekly":"Créer le plan hebdomadaire","Preview":"Aperçu","Daily Lesson Plan":"Plan de leçon quotidien","Weekly Lesson Plan":"Plan de leçon hebdomadaire","Chapter / Unit":"Chapitre / Unité","Date":"Date","Select week":"Sélectionner la semaine","Week Start Date":"Date de début de semaine","Week End Date":"Date de fin de semaine","Classroom":"Salle de classe","Number of Students":"Nombre d'élèves",
  "Curriculum suggestions":"Suggestions du programme","Apply first match":"Appliquer la première correspondance","Apply":"Appliquer","Objectives row":"Ligne des objectifs","Presentation row":"Ligne de présentation","Assessment row":"Ligne d'évaluation","Assessment":"Évaluation","Regenerate day":"Régénérer la journée","Lifecycle and history":"Cycle de vie et historique","Status, revision notes, and activity log.":"Statut, notes de révision et journal d'activité.","Revision note":"Note de révision","Explain what changed or what needs review...":"Expliquez ce qui a changé ou doit être révisé...","No activity logged yet.":"Aucune activité enregistrée pour le moment.","Print preview":"Aperçu avant impression","Scaled to fit the screen.":"Adapté à la taille de l'écran.","Print":"Imprimer","School":"École","Restore suggestion":"Restaurer la suggestion","Only the changing details are editable. KCS is already known.":"Seuls les détails variables sont modifiables. KCS est déjà renseigné.","Download failed":"Échec du téléchargement","Curriculum suggestions applied":"Suggestions du programme appliquées","Revision note added":"Note de révision ajoutée"
};

const patterns: Array<[RegExp, (...values: string[]) => string]> = [
  [/^Week (\d+)$/, value => `Semaine ${value}`],
  [/^(\d+) lesson plans?$/, count => `${count} plan${count === "1" ? "" : "s"} de leçon`],
  [/^Status updated to (.+)$/, status => `Statut mis à jour : ${translateToFrench(status)}`],
  [/^Workflow updated: (.+)$/, status => `Flux de travail mis à jour : ${translateToFrench(status)}`],
  [/^Saved checkpoint (\d+)$/, value => `Point de contrôle ${value} enregistré`],
  [/^(\d+) daily lesson plans created$/, count => `${count} plans de leçon quotidiens créés`],
  [/^Select (.+)$/, value => `Sélectionner ${value}`]
];

export const translateToFrench = (value: string): string => {
  if (fr[value]) return fr[value];
  for (const [pattern, replacement] of patterns) {
    const match = value.match(pattern);
    if (match) return replacement(...match.slice(1));
  }
  return value;
};