import { createBlankLesson, createFlexibleWeeklyPlan, isAutoGeneratedWeeklyPlan, schoolDisplayName, schoolName } from "../data/defaults";
import { LessonActivityAction, LessonFilters, LessonPlan, LessonStatus, WeeklyPlanDay } from "../types/lesson";
import { UserProfile } from "../types/user";

const key = "powerful-lesson-planner:lessons";

const read = (options: { includeDeleted?: boolean } = {}): LessonPlan[] => {
  try {
    const lessons = JSON.parse(localStorage.getItem(key) || "[]") as LessonPlan[];
    const normalized = lessons.map((lesson) => normalizeLesson(lesson));
    return options.includeDeleted ? normalized : normalized.filter((lesson) => !lesson.deletedAt);
  } catch {
    return [];
  }
};

const write = (lessons: LessonPlan[]) => {
  localStorage.setItem(key, JSON.stringify(lessons));
};

const readAll = () => read({ includeDeleted: true });

const normalizeLesson = (lesson: Partial<LessonPlan>): LessonPlan => {
  const base = createBlankLesson(lesson.lessonNumber || `LP-${new Date().getFullYear()}-0001`);
  const subject = lesson.subject || base.subject;
  const gradeClass = lesson.gradeClass || base.gradeClass;
  const chapter = isGeneratedLessonTitle(lesson.chapter) ? base.chapter : lesson.chapter || base.chapter;
  const weeklyPlan = normalizeWeeklyPlan(lesson.weeklyPlan, subject, gradeClass, chapter);
  const ownerId = lesson.ownerId || base.ownerId;
  const ownerName = lesson.ownerName || lesson.teachers || base.ownerName;
  const department = lesson.department || base.department;

  return {
    ...base,
    ...lesson,
    ownerId,
    ownerName,
    department,
    planType: lesson.planType || base.planType,
    status: normalizeStatus(lesson.status),
    schoolName: !lesson.schoolName || lesson.schoolName === schoolName || lesson.schoolName.includes("KINSHASA CHRISTIAN SCHOOL") ? schoolDisplayName : lesson.schoolName,
    schoolYear: lesson.schoolYear || base.schoolYear,
    semester: lesson.semester || base.semester,
    quarter: lesson.quarter || lesson.term || base.quarter,
    chapter,
    teachers: lesson.teachers || base.teachers,
    subject,
    gradeClass,
    duration: lesson.duration || base.duration,
    week: lesson.week || base.week,
    tags: lesson.tags || base.tags,
    learningObjectives: lesson.learningObjectives?.length ? lesson.learningObjectives : base.learningObjectives,
    learningOutcomes: lesson.learningOutcomes?.length ? lesson.learningOutcomes : base.learningOutcomes,
    successCriteria: lesson.successCriteria?.length ? lesson.successCriteria : base.successCriteria,
    materialsResources: lesson.materialsResources?.length ? lesson.materialsResources : base.materialsResources,
    vocabulary: lesson.vocabulary?.length ? lesson.vocabulary : base.vocabulary,
    safetyConsiderations: lesson.safetyConsiderations?.length ? lesson.safetyConsiderations : base.safetyConsiderations,
    stages: lesson.stages?.length ? lesson.stages : base.stages,
    blooms: { ...base.blooms, ...(lesson.blooms || {}) },
    differentiation: { ...base.differentiation, ...(lesson.differentiation || {}) },
    assessment: { ...base.assessment, ...(lesson.assessment || {}) },
    reflection: { ...base.reflection, ...(lesson.reflection || {}) },
    weeklyPlan,
    activityLogs: lesson.activityLogs || [],
    revisionNotes: lesson.revisionNotes || [],
    versions: lesson.versions || []
  };
};

const normalizeStatus = (status?: string): LessonStatus => {
  if (status === "active") return "draft";
  if (["draft", "submitted", "under-review", "approved", "rejected", "archived", "published"].includes(status || "")) {
    return status as LessonStatus;
  }
  return "draft";
};

const isGeneratedLessonTitle = (value?: string) => Boolean(value?.trim().toLowerCase().startsWith("weekly lesson plan"));

const normalizeWeeklyPlan = (weeklyPlan: Partial<WeeklyPlanDay>[] | undefined, subject: string, gradeClass: string, chapter: string): WeeklyPlanDay[] => {
  const base = createFlexibleWeeklyPlan(subject, gradeClass, chapter);

  if (isAutoGeneratedWeeklyPlan(weeklyPlan, subject, gradeClass, chapter)) {
    return base;
  }

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: weeklyPlan?.[index]?.lesson || day.lesson,
    objectives: weeklyPlan?.[index]?.objectives || day.objectives,
    presentation: weeklyPlan?.[index]?.presentation || day.presentation,
    guidedPractice: weeklyPlan?.[index]?.guidedPractice || day.guidedPractice,
    exitTicket: weeklyPlan?.[index]?.exitTicket || day.exitTicket,
    assessment: weeklyPlan?.[index]?.assessment || day.assessment,
    homework: weeklyPlan?.[index]?.homework || day.homework
  }));
};

export const lessonRepository = {
  list: read,
  listAll: readAll,
  get(id: string) {
    return readAll().find((lesson) => lesson.id === id && !lesson.deletedAt);
  },
  save(lesson: LessonPlan, actor?: UserProfile | null, description = "Lesson plan updated") {
    const lessons = readAll();
    const current = lessons.find((item) => item.id === lesson.id);
    const nextLesson = withActivity(
      { ...lesson, updatedAt: lesson.updatedAt || new Date().toISOString() },
      actor,
      current ? "updated" : "created",
      description,
      current?.status !== lesson.status ? { field: "status", oldValue: current?.status, newValue: lesson.status } : undefined
    );
    const next = lessons.some((item) => item.id === lesson.id)
      ? lessons.map((item) => (item.id === lesson.id ? nextLesson : item))
      : [nextLesson, ...lessons];
    write(next);
    return nextLesson;
  },
  duplicate(lesson: LessonPlan, actor: UserProfile, lessonNumber: string) {
    const now = new Date().toISOString();
    const copy = withActivity(
      {
        ...lesson,
        id: crypto.randomUUID(),
        ownerId: actor.id,
        ownerName: actor.name,
        department: actor.department,
        lessonNumber,
        topic: `${lesson.topic || "Untitled Lesson"} (Copy)`,
        status: "draft",
        deletedAt: undefined,
        deletedBy: undefined,
        deletedByName: undefined,
        createdAt: now,
        updatedAt: now,
        activityLogs: [],
        revisionNotes: [],
        versions: []
      },
      actor,
      "duplicated",
      `Duplicated from ${lesson.lessonNumber || lesson.id}`
    );
    write([copy, ...readAll()]);
    return copy;
  },
  changeStatus(id: string, status: LessonStatus, actor: UserProfile | null | undefined, description?: string) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return undefined;
    const action = actionForStatus(status, lesson.status);
    const now = new Date().toISOString();
    const next = withActivity(
      { ...lesson, status, updatedAt: now },
      actor,
      action,
      description || `Status changed from ${lesson.status} to ${status}`,
      { field: "status", oldValue: lesson.status, newValue: status }
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    return next;
  },
  addRevisionNote(id: string, note: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson || !note.trim()) return undefined;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      {
        ...lesson,
        updatedAt: timestamp,
        revisionNotes: [{ id: crypto.randomUUID(), ...user, timestamp, note: note.trim() }, ...(lesson.revisionNotes || [])]
      },
      actor,
      "revision-note",
      note.trim()
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    return next;
  },
  softDelete(id: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      { ...lesson, deletedAt: timestamp, deletedBy: user.userId, deletedByName: user.userName, updatedAt: timestamp },
      actor,
      "soft-deleted",
      "Lesson plan moved to deleted items"
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
  },
  restore(id: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return undefined;
    const next = withActivity(
      { ...lesson, deletedAt: undefined, deletedBy: undefined, deletedByName: undefined, updatedAt: new Date().toISOString() },
      actor,
      "restored",
      "Lesson plan restored from deleted items"
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    return next;
  },
  remove(id: string, actor?: UserProfile | null) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      { ...lesson, deletedAt: timestamp, deletedBy: user.userId, deletedByName: user.userName, updatedAt: timestamp },
      actor,
      "soft-deleted",
      "Lesson plan moved to deleted items"
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
  },
  import(lessons: LessonPlan[]) {
    write(lessons);
  },
  exportJson() {
    return JSON.stringify(readAll(), null, 2);
  }
};

const actionForStatus = (status: LessonStatus, oldStatus: LessonStatus): LessonActivityAction => {
  if (status === "submitted") return "submitted";
  if (status === "under-review") return "review-started";
  if (status === "approved") return "approved";
  if (status === "rejected") return "rejected";
  if (status === "published") return "published";
  if (status === "archived") return "archived";
  if (oldStatus === "archived") return "unarchived";
  return "status-changed";
};

const actorInfo = (actor?: UserProfile | null) => ({
  userId: actor?.id || "system",
  userName: actor?.name || "System"
});

const withActivity = (
  lesson: LessonPlan,
  actor: UserProfile | null | undefined,
  action: LessonActivityAction,
  description: string,
  change?: { field?: string; oldValue?: string; newValue?: string }
): LessonPlan => ({
  ...lesson,
  activityLogs: [
    {
      id: crypto.randomUUID(),
      ...actorInfo(actor),
      action,
      timestamp: new Date().toISOString(),
      field: change?.field,
      oldValue: change?.oldValue,
      newValue: change?.newValue,
      description
    },
    ...(lesson.activityLogs || [])
  ]
});

export const filterLessons = (lessons: LessonPlan[], filters: LessonFilters) => {
  const query = filters.query.trim().toLowerCase();
  const tags = filters.tags.toLowerCase().split(",").map((tag) => tag.trim()).filter(Boolean);

  return lessons.filter((lesson) => {
    const haystack = [
      lesson.schoolName,
      lesson.teachers,
      lesson.subject,
      lesson.gradeClass,
      lesson.topic,
      lesson.subtopic,
      lesson.chapter,
      lesson.schoolYear,
      lesson.semester,
      lesson.quarter,
      lesson.week,
      lesson.term,
      lesson.tags.join(" "),
      lesson.learningObjectives.map((item) => item.value).join(" "),
      lesson.weeklyPlan?.map((day) => Object.values(day).join(" ")).join(" ")
    ].join(" ").toLowerCase();
    const month = lesson.date ? String(new Date(lesson.date).getMonth() + 1).padStart(2, "0") : "";
    const year = lesson.date ? String(new Date(lesson.date).getFullYear()) : "";

    return (
      (!query || haystack.includes(query)) &&
      (!filters.teacher || lesson.teachers.toLowerCase().includes(filters.teacher.toLowerCase())) &&
      (!filters.subject || lesson.subject.toLowerCase().includes(filters.subject.toLowerCase())) &&
      (!filters.grade || lesson.gradeClass.toLowerCase().includes(filters.grade.toLowerCase())) &&
      (!filters.date || lesson.date === filters.date) &&
      (!filters.topic || lesson.topic.toLowerCase().includes(filters.topic.toLowerCase())) &&
      (!filters.week || lesson.week === filters.week) &&
      (!filters.month || month === filters.month.padStart(2, "0")) &&
      (!filters.year || year === filters.year) &&
      (!filters.term || lesson.term.toLowerCase().includes(filters.term.toLowerCase())) &&
      (!tags.length || tags.every((tag) => lesson.tags.join(" ").toLowerCase().includes(tag))) &&
      (filters.status === "all" || lesson.status === filters.status)
    );
  });
};
