import { createBlankLesson, createFlexibleWeeklyPlan, isAutoGeneratedWeeklyPlan, schoolDisplayName, schoolName } from "../data/defaults";
import { LessonFilters, LessonPlan, WeeklyPlanDay } from "../types/lesson";

const key = "powerful-lesson-planner:lessons";

const read = (): LessonPlan[] => {
  try {
    const lessons = JSON.parse(localStorage.getItem(key) || "[]") as LessonPlan[];
    return lessons.map(normalizeLesson);
  } catch {
    return [];
  }
};

const write = (lessons: LessonPlan[]) => {
  localStorage.setItem(key, JSON.stringify(lessons));
};

const normalizeLesson = (lesson: Partial<LessonPlan>): LessonPlan => {
  const base = createBlankLesson(lesson.lessonNumber || `LP-${new Date().getFullYear()}-0001`);
  const subject = lesson.subject || base.subject;
  const gradeClass = lesson.gradeClass || base.gradeClass;
  const chapter = lesson.chapter || lesson.topic || base.chapter;
  const weeklyPlan = normalizeWeeklyPlan(lesson.weeklyPlan, subject, gradeClass, chapter);

  return {
    ...base,
    ...lesson,
    schoolName: !lesson.schoolName || lesson.schoolName === schoolName || lesson.schoolName.includes("KINSHASA CHRISTIAN SCHOOL") ? schoolDisplayName : lesson.schoolName,
    schoolYear: lesson.schoolYear || base.schoolYear,
    semester: lesson.semester || base.semester,
    quarter: lesson.quarter || lesson.term || base.quarter,
    chapter,
    teachers: lesson.teachers || base.teachers,
    subject,
    gradeClass,
    duration: lesson.duration || base.duration,
    week: lesson.week || base.week,
    tags: lesson.tags || base.tags,
    learningObjectives: lesson.learningObjectives?.length ? lesson.learningObjectives : base.learningObjectives,
    learningOutcomes: lesson.learningOutcomes?.length ? lesson.learningOutcomes : base.learningOutcomes,
    successCriteria: lesson.successCriteria?.length ? lesson.successCriteria : base.successCriteria,
    materialsResources: lesson.materialsResources?.length ? lesson.materialsResources : base.materialsResources,
    vocabulary: lesson.vocabulary?.length ? lesson.vocabulary : base.vocabulary,
    safetyConsiderations: lesson.safetyConsiderations?.length ? lesson.safetyConsiderations : base.safetyConsiderations,
    stages: lesson.stages?.length ? lesson.stages : base.stages,
    blooms: { ...base.blooms, ...(lesson.blooms || {}) },
    differentiation: { ...base.differentiation, ...(lesson.differentiation || {}) },
    assessment: { ...base.assessment, ...(lesson.assessment || {}) },
    reflection: { ...base.reflection, ...(lesson.reflection || {}) },
    weeklyPlan,
    versions: lesson.versions || []
  };
};

const normalizeWeeklyPlan = (weeklyPlan: Partial<WeeklyPlanDay>[] | undefined, subject: string, gradeClass: string, chapter: string): WeeklyPlanDay[] => {
  const base = createFlexibleWeeklyPlan(subject, gradeClass, chapter);

  if (isAutoGeneratedWeeklyPlan(weeklyPlan, subject, gradeClass, chapter)) {
    return base;
  }

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: weeklyPlan?.[index]?.lesson || day.lesson,
    objectives: weeklyPlan?.[index]?.objectives || day.objectives,
    presentation: weeklyPlan?.[index]?.presentation || day.presentation,
    guidedPractice: weeklyPlan?.[index]?.guidedPractice || day.guidedPractice,
    exitTicket: weeklyPlan?.[index]?.exitTicket || day.exitTicket,
    assessment: weeklyPlan?.[index]?.assessment || day.assessment,
    homework: weeklyPlan?.[index]?.homework || day.homework
  }));
};

export const lessonRepository = {
  list: read,
  get(id: string) {
    return read().find((lesson) => lesson.id === id);
  },
  save(lesson: LessonPlan) {
    const lessons = read();
    const next = lessons.some((item) => item.id === lesson.id)
      ? lessons.map((item) => (item.id === lesson.id ? lesson : item))
      : [lesson, ...lessons];
    write(next);
    return lesson;
  },
  remove(id: string) {
    write(read().filter((lesson) => lesson.id !== id));
  },
  import(lessons: LessonPlan[]) {
    write(lessons);
  },
  exportJson() {
    return JSON.stringify(read(), null, 2);
  }
};

export const filterLessons = (lessons: LessonPlan[], filters: LessonFilters) => {
  const query = filters.query.trim().toLowerCase();
  const tags = filters.tags.toLowerCase().split(",").map((tag) => tag.trim()).filter(Boolean);

  return lessons.filter((lesson) => {
    const haystack = [
      lesson.schoolName,
      lesson.teachers,
      lesson.subject,
      lesson.gradeClass,
      lesson.topic,
      lesson.subtopic,
      lesson.chapter,
      lesson.schoolYear,
      lesson.semester,
      lesson.quarter,
      lesson.week,
      lesson.term,
      lesson.tags.join(" "),
      lesson.learningObjectives.map((item) => item.value).join(" "),
      lesson.weeklyPlan?.map((day) => Object.values(day).join(" ")).join(" ")
    ].join(" ").toLowerCase();
    const month = lesson.date ? String(new Date(lesson.date).getMonth() + 1).padStart(2, "0") : "";
    const year = lesson.date ? String(new Date(lesson.date).getFullYear()) : "";

    return (
      (!query || haystack.includes(query)) &&
      (!filters.teacher || lesson.teachers.toLowerCase().includes(filters.teacher.toLowerCase())) &&
      (!filters.subject || lesson.subject.toLowerCase().includes(filters.subject.toLowerCase())) &&
      (!filters.grade || lesson.gradeClass.toLowerCase().includes(filters.grade.toLowerCase())) &&
      (!filters.date || lesson.date === filters.date) &&
      (!filters.topic || lesson.topic.toLowerCase().includes(filters.topic.toLowerCase())) &&
      (!filters.week || lesson.week === filters.week) &&
      (!filters.month || month === filters.month.padStart(2, "0")) &&
      (!filters.year || year === filters.year) &&
      (!filters.term || lesson.term.toLowerCase().includes(filters.term.toLowerCase())) &&
      (!tags.length || tags.every((tag) => lesson.tags.join(" ").toLowerCase().includes(tag))) &&
      (filters.status === "all" || lesson.status === filters.status)
    );
  });
};
