import { zodResolver } from "@hookform/resolvers/zod";
import { Copy, Download, FileDown, Loader2, Printer, Save, Sparkles, Trash2 } from "lucide-react";
import { CSSProperties, useEffect, useMemo, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { useReactToPrint } from "react-to-print";
import { useNavigate, useParams } from "react-router-dom";
import { z } from "zod";
import { useToast } from "../components/Toast";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Dialog } from "../components/ui/dialog";
import { Input, Select, Textarea } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { useAuth } from "../contexts/AuthContext";
import {
  createAutomaticLessonSupport,
  createBlankLesson,
  createFlexibleWeeklyPlan,
  isAutoGeneratedWeeklyPlan,
  schoolDisplayName,
  schoolImage
} from "../data/defaults";
import { useDebouncedEffect } from "../hooks/useDebouncedEffect";
import { LessonPrint } from "../print/LessonPrint";
import { curriculumRepository, findCurriculumSuggestions } from "../services/curriculumRepository";
import { lessonRepository } from "../services/lessonRepository";
import { canDeleteLesson, canEditLesson, canReviewLesson, canViewLesson, prepareNewLessonForUser } from "../services/permissions";
import { LessonPlan, WeeklyPlanDay } from "../types/lesson";
import { exportElementToDocx, exportElementToPdf } from "../utils/export";

const schema = z.object({
  teachers: z.string().min(1, "Teacher is required"),
  subject: z.string().min(1, "Subject is required"),
  gradeClass: z.string().min(1, "Grade/Class is required"),
  chapter: z.string().min(1, "Chapter is required")
}).passthrough();

const weekOptions = Array.from({ length: 40 }, (_, index) => String(index + 1));
const durationOptions = ["30 min", "45 min", "50 min", "60 min", "1h", "1h15", "1h30", "2h"];
const semesterOptions = ["1st", "2nd"];
const quarterOptions = ["1st", "2nd", "3rd", "4th"];
const currentSchoolYear = new Date().getFullYear() - 1;
const schoolYearOptions = Array.from({ length: 8 }, (_, index) => {
  const start = currentSchoolYear + index;
  return `${start}-${start + 1}`;
});
type SetupField =
  | "planType"
  | "teachers"
  | "subject"
  | "gradeClass"
  | "chapter"
  | "date"
  | "week"
  | "weekStartDate"
  | "weekEndDate"
  | "duration"
  | "schoolYear"
  | "semester"
  | "quarter"
  | "term"
  | "classroom"
  | "numberOfStudents";

export const Editor = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { notify } = useToast();
  const { currentUser, can } = useAuth();
  const [preview, setPreview] = useState(false);
  const [exporting, setExporting] = useState<"pdf" | "docx" | null>(null);
  const [revisionNote, setRevisionNote] = useState("");
  const printRef = useRef<HTMLDivElement>(null);
  const lesson = useMemo(() => (id ? lessonRepository.get(id) : undefined), [id]);
  const fallback = useMemo(() => createBlankLesson(`LP-${new Date().getFullYear()}-0001`), []);
  const canViewCurrent = lesson ? canViewLesson(currentUser, lesson) : true;
  const canEditCurrent = lesson ? canEditLesson(currentUser, lesson) : can("lesson:create");
  const canDeleteCurrent = lesson ? canDeleteLesson(currentUser, lesson) : false;
  const canReviewCurrent = lesson ? canReviewLesson(currentUser, lesson) : false;

  const form = useForm<LessonPlan>({
    defaultValues: lesson || fallback,
    resolver: zodResolver(schema),
    mode: "onChange"
  });
  const previousSetupRef = useRef({
    subject: (lesson || fallback).subject,
    gradeClass: (lesson || fallback).gradeClass,
    chapter: sanitizeChapter((lesson || fallback).chapter)
  });
  const previousAutoObjectivesRef = useRef<string[]>([]);
  const values = form.watch();
  const currentChapter = sanitizeChapter(values.chapter);
  const planType = values.planType || "weekly";
  const weeklyPlan = normalizeEditableWeeklyPlan(values.weeklyPlan, values.subject, values.gradeClass, currentChapter);
  const displayedPlan = planType === "daily" ? weeklyPlan.slice(0, 1) : weeklyPlan;
  const lessonSignature = weeklyPlan.map((day) => day.lesson).join("|");
  const printableLesson = toPrintableLesson(values);
  const curriculumItems = useMemo(() => curriculumRepository.list(), []);
  const curriculumSuggestions = useMemo(() => findCurriculumSuggestions(curriculumItems, values.gradeClass, values.subject), [curriculumItems, values.gradeClass, values.subject]);
  const unitOptions = useMemo(() => unique([...curriculumSuggestions.map((item) => item.unit), currentChapter].filter(Boolean)), [curriculumSuggestions, currentChapter]);
  const topicOptions = useMemo(() => unique(curriculumSuggestions.map((item) => item.topic).filter(Boolean)), [curriculumSuggestions]);
  const subtopicOptions = useMemo(() => unique(curriculumSuggestions.map((item) => item.subtopic).filter(Boolean)), [curriculumSuggestions]);

  useEffect(() => {
    const current = form.getValues();
    const chapter = sanitizeChapter(current.chapter);
    const hasSetup = Boolean(current.subject || current.gradeClass || chapter);
    const support = createAutomaticLessonSupport(current.subject, current.gradeClass, chapter);
    const previousSetup = previousSetupRef.current;
    const planCanSync =
      isAutoGeneratedWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, chapter) ||
      isAutoGeneratedWeeklyPlan(current.weeklyPlan, previousSetup.subject, previousSetup.gradeClass, previousSetup.chapter);

    previousSetupRef.current = {
      subject: current.subject,
      gradeClass: current.gradeClass,
      chapter
    };

    if (!hasSetup) return;

    if (planCanSync) {
      form.setValue("weeklyPlan", createFlexibleWeeklyPlan(current.subject, current.gradeClass, chapter), {
        shouldDirty: true,
        shouldValidate: false
      });

    }

    const nextTitle = buildAutomaticTitle(current);
    const titleCanSync = true;

    if (titleCanSync && nextTitle !== current.topic) {
      form.setValue("topic", nextTitle, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.learningObjectives)) {
      form.setValue("learningObjectives", support.learningObjectives.map((value, index) => ({ id: `auto-objective-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.learningOutcomes)) {
      form.setValue("learningOutcomes", support.learningOutcomes.map((value, index) => ({ id: `auto-outcome-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.successCriteria)) {
      form.setValue("successCriteria", support.successCriteria.map((value, index) => ({ id: `auto-criteria-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.vocabulary)) {
      form.setValue("vocabulary", [{ id: "vocabulary", value: support.vocabulary }], {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.materialsResources)) {
      form.setValue("materialsResources", [{ id: "materials", value: support.materialsResources }], {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.differentiation?.inclusiveStrategies?.trim()) {
      form.setValue("differentiation.inclusiveStrategies", support.differentiation, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.assessment?.teacherComments?.trim()) {
      form.setValue("assessment.teacherComments", support.assessment, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.reflection?.teacherNotes?.trim()) {
      form.setValue("reflection.teacherNotes", support.reflection, {
        shouldDirty: true,
        shouldValidate: false
      });
    }
  }, [form, values.subject, values.gradeClass, values.chapter, values.week, values.planType]);

  useEffect(() => {
    const current = form.getValues();
    const currentPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    let changed = false;

    const nextPlan = currentPlan.map((day, index) => {
      const autoObjective = createDailyObjective(day.lesson, current.subject, current.gradeClass);
      const previousAutoObjective = previousAutoObjectivesRef.current[index];
      const currentObjective = day.objectives || "";
      const objectiveCanSync =
        !currentObjective.trim() ||
        currentObjective === previousAutoObjective ||
        isGenericObjective(currentObjective, current.gradeClass, sanitizeChapter(current.chapter));

      previousAutoObjectivesRef.current[index] = autoObjective;

      if (!day.day || objectiveCanSync) {
        changed = changed || day.day !== weeklyPlan[index]?.day || currentObjective !== autoObjective;
        return {
          ...day,
          day: day.day || weeklyPlan[index]?.day || day.day,
          objectives: objectiveCanSync ? autoObjective : currentObjective
        };
      }

      return day;
    });

    if (changed) {
      form.setValue("weeklyPlan", nextPlan, {
        shouldDirty: true,
        shouldValidate: false
      });
    }
  }, [form, lessonSignature, values.subject, values.gradeClass, values.chapter, values.topic]);

  const completion = useMemo(() => {
    const required = [
      values.teachers,
      values.subject,
      values.gradeClass,
      values.chapter,
      ...displayedPlan.flatMap((day) => [day.lesson, day.objectives, day.presentation, day.assessment])
    ];
    return Math.round((required.filter(Boolean).length / required.length) * 100);
  }, [displayedPlan, values]);

  const save = (withVersion = false) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const now = new Date().toISOString();
    const next: LessonPlan = {
      ...toPrintableLesson(current),
      updatedAt: now,
      versions: withVersion
        ? [{ id: crypto.randomUUID(), savedAt: now, summary: `Manual save: ${current.chapter || current.topic}`, snapshot: { ...current, versions: [] } }, ...(current.versions || [])].slice(0, 20)
        : current.versions || []
    };
    lessonRepository.save(next, currentUser, withVersion ? "Manual save with revision snapshot" : "Autosaved lesson changes");
    if (withVersion) {
      form.reset(next);
      notify("Saved");
    }
  };

  useDebouncedEffect(() => {
    if (canEditCurrent && form.formState.isDirty) save(false);
  }, [values, canEditCurrent], 900);

  const printTitle = printableLesson.topic || printableLesson.chapter || "lesson-plan";
  const print = useReactToPrint({ contentRef: printRef, documentTitle: printTitle });

  const exportDocument = async (type: "pdf" | "docx") => {
    if (!printRef.current || exporting) return;
    setExporting(type);
    notify(type === "pdf" ? "Téléchargement PDF en cours..." : "Téléchargement DOCX en cours...");
    try {
      if (type === "pdf") {
        await exportElementToPdf(printRef.current, `${printTitle}.pdf`);
      } else {
        await exportElementToDocx(printRef.current, `${printTitle}.docx`);
      }
      notify(type === "pdf" ? "PDF téléchargé" : "DOCX téléchargé");
    } catch {
      notify("Le téléchargement a échoué");
    } finally {
      setExporting(null);
    }
  };

  const duplicate = () => {
    if (!currentUser) return;
    const now = new Date().toISOString();
    const copy = prepareNewLessonForUser({
      ...form.getValues(),
      id: crypto.randomUUID(),
      ownerId: "",
      ownerName: "",
      department: "",
      lessonNumber: `LP-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`,
      createdAt: now,
      updatedAt: now,
      versions: []
    }, currentUser);
    lessonRepository.save(copy, currentUser, "Lesson plan duplicated from editor");
    notify("Duplicated lesson plan");
    navigate(`/editor/${copy.id}`);
  };

  const generateWeek = () => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const subject = current.subject || "";
    const chapter = sanitizeChapter(current.chapter);
    const grade = current.gradeClass || "";
    const generated: WeeklyPlanDay[] = createFlexibleWeeklyPlan(subject, grade, chapter);
    form.setValue("weeklyPlan", generated, { shouldDirty: true });
    const generatedTitle = buildAutomaticTitle({ ...current, subject, gradeClass: grade, chapter, planType });
    form.setValue("topic", generatedTitle, { shouldDirty: true });
    notify(planType === "daily" ? "Daily lesson generated automatically" : "Week generated automatically");
  };

  const updateWeeklyDay = (index: number, key: keyof Omit<WeeklyPlanDay, "day">, value: string) => {
    if (!canEditCurrent) return;
    const next = normalizeEditableWeeklyPlan(form.getValues().weeklyPlan, form.getValues().subject, form.getValues().gradeClass, sanitizeChapter(form.getValues().chapter));
    next[index] = {
      ...next[index],
      [key]: value
    };
    form.setValue("weeklyPlan", next, {
      shouldDirty: true,
      shouldValidate: false
    });
  };

  const updateSetupField = (field: SetupField, value: string) => {
    if (!canEditCurrent) return;
    if (field === "weekStartDate") {
      form.setValue("weekEndDate", addBusinessWeekEnd(value), {
        shouldDirty: true,
        shouldValidate: false
      });
    }
    form.setValue(field, value, {
      shouldDirty: true,
      shouldValidate: false
    });
  };

  const applyCurriculumItem = (item = curriculumSuggestions[0]) => {
    if (!item || !canEditCurrent) return;
    form.setValue("chapter", item.unit, { shouldDirty: true });
    form.setValue("topic", item.topic, { shouldDirty: true });
    form.setValue("subtopic", item.subtopic, { shouldDirty: true });
    form.setValue("learningObjectives", item.learningObjectives.map((value, index) => ({ id: `curriculum-objective-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("learningOutcomes", item.learningOutcomes.map((value, index) => ({ id: `curriculum-outcome-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("referenceBook", item.references.join("; "), { shouldDirty: true });
    form.setValue("vocabulary", item.skills.map((value, index) => ({ id: `curriculum-skill-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("crossCurricularConnections", [
      item.competencies.length ? `Competencies: ${item.competencies.join("; ")}` : "",
      item.curriculumStandards.length ? `Standards: ${item.curriculumStandards.join("; ")}` : ""
    ].filter(Boolean).join("\n"), { shouldDirty: true });
    notify("Curriculum suggestions applied");
  };

  if (!canViewCurrent) {
    return (
      <Card className="mx-auto mt-10 max-w-xl p-8 text-center">
        <p className="text-xs font-black uppercase text-cyan-200">Access restricted</p>
        <h1 className="mt-2 text-2xl font-black text-white">You do not have permission to view this lesson plan.</h1>
        <p className="mt-2 text-sm text-muted-foreground">Switch to an authorized role or return to the visible lesson plan library.</p>
        <Button className="mt-5" onClick={() => navigate("/plans")}>Back to plans</Button>
      </Card>
    );
  }

  return (
    <div className="min-w-0 space-y-4 overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="min-w-0">
          <p className="text-xs font-black uppercase text-cyan-200">KCS {planType === "daily" ? "daily" : "weekly"} lesson plan</p>
          <h1 className="truncate text-2xl font-black text-white md:text-3xl">{printableLesson.topic || printableLesson.chapter || printableLesson.subject || "New Lesson Plan"}</h1>
          <p className="text-sm text-muted-foreground">
            KCS stays fixed; the title, lesson details, and teaching content come from your fields.
            {!canEditCurrent && " This plan is read-only for your current role."}
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Owner: {printableLesson.ownerName || printableLesson.teachers || "Unassigned"} · Department: {printableLesson.department || "Unassigned"}
            {canReviewCurrent ? " · Department review enabled" : ""}
          </p>
        </div>
        <div className="flex min-w-0 flex-wrap gap-2">
          {canEditCurrent && <Button variant="outline" onClick={() => save(true)}><Save size={17} /> Save</Button>}
          {can("lesson:create") && <Button variant="outline" onClick={duplicate}><Copy size={17} /> Duplicate</Button>}
          <Button variant="outline" onClick={() => setPreview(true)}><Printer size={17} /> Preview</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("pdf")}>{exporting === "pdf" ? <Loader2 className="animate-spin" size={17} /> : <FileDown size={17} />} {exporting === "pdf" ? "PDF..." : "PDF"}</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("docx")}>{exporting === "docx" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />} {exporting === "docx" ? "DOCX..." : "DOCX"}</Button>
          {canDeleteCurrent && <Button variant="danger" onClick={() => { if (confirm("Move this lesson plan to deleted items?")) { lessonRepository.remove(values.id, currentUser); navigate("/plans"); } }}><Trash2 size={17} /></Button>}
        </div>
      </div>

      <div className="h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{ width: `${completion}%` }} /></div>

      <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(320px,380px)]">
        <form className="min-w-0 space-y-4" onSubmit={form.handleSubmit(() => save(true))}>
          <fieldset disabled={!canEditCurrent} className="min-w-0 space-y-4 disabled:opacity-75">
          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">1. Essential setup</h2>
                <p className="text-sm text-muted-foreground">Only the changing details are editable. KCS is already known.</p>
              </div>
              <div className="flex gap-2">
                <Button type="button" variant="secondary" onClick={generateWeek}><Sparkles size={17} /> {planType === "daily" ? "Generate day" : "Generate week"}</Button>
              </div>
            </div>
            <div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              <Field label="Plan Type">
                <Select value={planType} onChange={(event) => updateSetupField("planType", event.target.value)}>
                  <option value="weekly">Weekly Lesson Plan</option>
                  <option value="daily">Daily Lesson Plan</option>
                </Select>
              </Field>
              <Field label="Lesson Plan Title"><Input readOnly value={printableLesson.topic} className="bg-white/[0.03]" /></Field>
              <LockedSchool />
              <Field label="Teacher"><Input value={values.teachers || ""} onChange={(event) => updateSetupField("teachers", event.target.value)} /></Field>
              <Field label="Subject"><Input list="subject-suggestions" value={values.subject || ""} onChange={(event) => updateSetupField("subject", event.target.value)} /></Field>
              <Field label="Grade"><Input list="grade-suggestions" value={values.gradeClass || ""} onChange={(event) => updateSetupField("gradeClass", event.target.value)} /></Field>
              <Field label="Chapter / Unit"><Input list="unit-suggestions" value={values.chapter || ""} onChange={(event) => updateSetupField("chapter", event.target.value)} /></Field>
              <Field label="Date"><Input type="date" value={values.date || ""} onChange={(event) => updateSetupField("date", event.target.value)} /></Field>
              {planType === "weekly" && <Field label="Week">
                <Select value={values.week || "1"} onChange={(event) => updateSetupField("week", event.target.value)}>
                  {weekOptions.map((week) => <option key={week} value={week}>Week {week}</option>)}
                </Select>
              </Field>}
              {planType === "weekly" && <Field label="Week Start Date"><Input type="date" value={values.weekStartDate || ""} onChange={(event) => updateSetupField("weekStartDate", event.target.value)} /></Field>}
              {planType === "weekly" && <Field label="Week End Date"><Input type="date" value={values.weekEndDate || ""} onChange={(event) => updateSetupField("weekEndDate", event.target.value)} /></Field>}
              {planType === "weekly" && <div className="rounded-md border border-cyan-300/20 bg-cyan-500/10 px-3 py-2 text-sm font-bold text-cyan-100 md:col-span-2 xl:col-span-3">
                {formatWeekRangeLabel(values.week, values.weekStartDate, values.weekEndDate)}
              </div>}
              <Field label="Duration">
                <Select value={values.duration || "45 min"} onChange={(event) => updateSetupField("duration", event.target.value)}>
                  {durationOptions.map((duration) => <option key={duration} value={duration}>{duration}</option>)}
                </Select>
              </Field>
              <Field label="School Year">
                <Select value={normalizeSchoolYear(values.schoolYear) || schoolYearOptions[0]} onChange={(event) => updateSetupField("schoolYear", event.target.value)}>
                  {normalizeSchoolYear(values.schoolYear) && !schoolYearOptions.includes(normalizeSchoolYear(values.schoolYear)) && (
                    <option value={normalizeSchoolYear(values.schoolYear)}>{normalizeSchoolYear(values.schoolYear)}</option>
                  )}
                  {schoolYearOptions.map((schoolYear) => <option key={schoolYear} value={schoolYear}>{schoolYear}</option>)}
                </Select>
              </Field>
              <Field label="Semester">
                <Select value={values.semester || "1st"} onChange={(event) => updateSetupField("semester", event.target.value)}>
                  {semesterOptions.map((semester) => <option key={semester} value={semester}>{semester} Semester</option>)}
                </Select>
              </Field>
              <Field label="Quarter">
                <Select value={values.quarter || "1st"} onChange={(event) => updateSetupField("quarter", event.target.value)}>
                  {quarterOptions.map((quarter) => <option key={quarter} value={quarter}>{quarter} Quarter</option>)}
                </Select>
              </Field>
              <Field label="Term"><Input value={values.term || ""} onChange={(event) => updateSetupField("term", event.target.value)} /></Field>
              <Field label="Classroom"><Input value={values.classroom || ""} onChange={(event) => updateSetupField("classroom", event.target.value)} /></Field>
              <Field label="Number of Students"><Input value={values.numberOfStudents || ""} onChange={(event) => updateSetupField("numberOfStudents", event.target.value)} /></Field>
            </div>
            <datalist id="subject-suggestions">
              {["Mathematics", "English", "English (Writing and Grammar)", "Science", "French", "Computer Science", "History", "Geography", "Physics", "Chemistry", "Biology", "Art", "Music", "Physical Education"].map((item) => <option key={item} value={item} />)}
            </datalist>
            <datalist id="grade-suggestions">
              {["K3", "K4", "K5", ...Array.from({ length: 12 }, (_, i) => `Grade ${i + 1}`)].map((item) => <option key={item} value={item} />)}
            </datalist>
            <datalist id="unit-suggestions">
              {unitOptions.map((item) => <option key={item} value={item} />)}
            </datalist>
          </Card>

          {curriculumSuggestions.length > 0 && (
            <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
              <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-black text-white">Curriculum suggestions</h2>
                  <p className="text-sm text-muted-foreground">Suggestions for {values.gradeClass || "grade"} and {values.subject || "subject"}.</p>
                </div>
                {canEditCurrent && <Button type="button" variant="outline" onClick={() => applyCurriculumItem()}><Sparkles size={17} /> Apply first match</Button>}
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <Field label="Topic suggestion"><Input list="topic-suggestions" value={values.topic || ""} onChange={(event) => form.setValue("topic", event.target.value, { shouldDirty: true })} /></Field>
                <Field label="Subtopic suggestion"><Input list="subtopic-suggestions" value={values.subtopic || ""} onChange={(event) => form.setValue("subtopic", event.target.value, { shouldDirty: true })} /></Field>
              </div>
              <div className="mt-3 grid gap-3">
                {curriculumSuggestions.slice(0, 4).map((item) => (
                  <div key={item.id} className="rounded-md border border-cyan-300/15 bg-cyan-500/10 p-3">
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <div>
                        <p className="text-xs font-black uppercase text-cyan-200">{item.academicYear} - {item.term}</p>
                        <p className="font-black text-white">{item.unit}: {item.topic}</p>
                        <p className="text-sm text-muted-foreground">{item.subtopic}</p>
                      </div>
                      {canEditCurrent && <Button type="button" variant="outline" onClick={() => applyCurriculumItem(item)}>Apply</Button>}
                    </div>
                    <p className="mt-2 text-sm text-muted-foreground">Objectives: {item.learningObjectives.slice(0, 2).join("; ")}</p>
                    <p className="mt-1 text-xs text-muted-foreground">Competencies: {item.competencies.join("; ") || "None"} - Standards: {item.curriculumStandards.join("; ") || "None"}</p>
                  </div>
                ))}
              </div>
              <datalist id="topic-suggestions">{topicOptions.map((item) => <option key={item} value={item} />)}</datalist>
              <datalist id="subtopic-suggestions">{subtopicOptions.map((item) => <option key={item} value={item} />)}</datalist>
            </Card>
          )}

          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-4">
              <h2 className="text-lg font-black text-white">2. Print notes and support</h2>
              <p className="text-sm text-muted-foreground">These fields are editable and appear in the final document.</p>
            </div>
            <div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              <Field label="Learning Objectives">
                <Textarea
                  className="min-h-28"
                  value={values.learningObjectives?.map((item) => item.value).join("\n") || ""}
                  onChange={(e) => form.setValue("learningObjectives", textToItems(e.target.value, "objective"), { shouldDirty: true })}
                />
              </Field>
              <Field label="Key Vocabulary">
                <Textarea
                  className="min-h-28"
                  value={values.vocabulary?.map((item) => item.value).join("; ") || ""}
                  onChange={(e) => form.setValue("vocabulary", [{ id: "vocabulary", value: e.target.value }], { shouldDirty: true })}
                />
              </Field>
              <Field label="Materials / Resources">
                <Textarea
                  className="min-h-28"
                  value={values.materialsResources?.map((item) => item.value).join("; ") || ""}
                  onChange={(e) => form.setValue("materialsResources", [{ id: "materials", value: e.target.value }], { shouldDirty: true })}
                />
              </Field>
              <Field label="References"><Textarea className="min-h-24" {...form.register("referenceBook")} /></Field>
              <Field label="Differentiation"><Textarea className="min-h-24" {...form.register("differentiation.inclusiveStrategies")} /></Field>
              <Field label="Assessment Notes"><Textarea className="min-h-24" {...form.register("assessment.teacherComments")} /></Field>
              <Field label="Reflection"><Textarea className="min-h-24" {...form.register("reflection.teacherNotes")} /></Field>
            </div>
          </Card>

          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-4">
              <h2 className="text-lg font-black text-white">3. {planType === "daily" ? "Daily lesson" : "Weekly grid"}</h2>
              <p className="text-sm text-muted-foreground">{planType === "daily" ? "Edit the single lesson for the selected date." : "Use Generate week first, then edit only the parts that need teacher judgement."}</p>
            </div>
            <div className={`grid min-w-0 grid-cols-1 gap-3 ${planType === "weekly" ? "md:grid-cols-2 2xl:grid-cols-5" : ""}`}>
              {displayedPlan.map((day, index) => (
                <div key={day.day} className="theme-dark-panel min-w-0 rounded-lg border border-cyan-300/15 bg-[#030d14]/70 p-3">
                  <h3 className="mb-3 rounded-md border border-cyan-300/20 bg-cyan-500/10 px-3 py-2 text-center text-sm font-black text-cyan-100">{planType === "daily" ? "Daily Lesson" : day.day}</h3>
                  <div className="space-y-2">
                    <Field label="Lesson"><Textarea className="min-h-16" value={day.lesson} onChange={(event) => updateWeeklyDay(index, "lesson", event.target.value)} /></Field>
                    <Field label="Objectives"><Textarea className="min-h-20" value={day.objectives} onChange={(event) => updateWeeklyDay(index, "objectives", event.target.value)} /></Field>
                    <Field label="Presentation"><Textarea className="min-h-20" value={day.presentation} onChange={(event) => updateWeeklyDay(index, "presentation", event.target.value)} /></Field>
                    <details>
                      <summary className="cursor-pointer rounded-md border border-cyan-300/15 px-3 py-2 text-xs font-bold text-cyan-100">More for this day</summary>
                      <div className="mt-2 space-y-2">
                        <Field label="Guided Practice"><Textarea className="min-h-16" value={day.guidedPractice} onChange={(event) => updateWeeklyDay(index, "guidedPractice", event.target.value)} /></Field>
                        <Field label="Exit Ticket"><Textarea className="min-h-16" value={day.exitTicket} onChange={(event) => updateWeeklyDay(index, "exitTicket", event.target.value)} /></Field>
                        <Field label="Assessment"><Textarea className="min-h-16" value={day.assessment} onChange={(event) => updateWeeklyDay(index, "assessment", event.target.value)} /></Field>
                        <Field label="Homework"><Textarea className="min-h-16" value={day.homework} onChange={(event) => updateWeeklyDay(index, "homework", event.target.value)} /></Field>
                      </div>
                    </details>
                  </div>
                </div>
              ))}
            </div>
          </Card>
          </fieldset>
        </form>

        <aside className="space-y-4">
          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-3 flex items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">Lifecycle and history</h2>
                <p className="text-xs text-muted-foreground">Status, revision notes, and activity log.</p>
              </div>
              <span className="rounded-full border border-cyan-300/25 bg-cyan-500/10 px-3 py-1 text-xs font-black uppercase text-cyan-100">{statusLabel(values.status)}</span>
            </div>
            {canEditCurrent && (
              <div className="mb-4 space-y-2">
                <Label>Revision note</Label>
                <Textarea className="min-h-20" value={revisionNote} onChange={(event) => setRevisionNote(event.target.value)} placeholder="Explain what changed or what needs review..." />
                <Button
                  variant="outline"
                  onClick={() => {
                    const next = lessonRepository.addRevisionNote(values.id, revisionNote, currentUser);
                    if (next) form.reset(next);
                    setRevisionNote("");
                    notify("Revision note added");
                  }}
                  disabled={!revisionNote.trim()}
                >
                  Add note
                </Button>
              </div>
            )}
            <div className="space-y-3">
              {(values.revisionNotes || []).slice(0, 3).map((note) => (
                <div key={note.id} className="rounded-md border border-cyan-300/15 bg-white/[0.04] p-3 text-sm">
                  <p className="font-bold text-white">{note.userName}</p>
                  <p className="text-xs text-muted-foreground">{new Date(note.timestamp).toLocaleString()}</p>
                  <p className="mt-1">{note.note}</p>
                </div>
              ))}
              {(values.activityLogs || []).slice(0, 5).map((log) => (
                <div key={log.id} className="rounded-md border border-cyan-300/10 px-3 py-2 text-xs text-muted-foreground">
                  <p><span className="font-bold text-foreground">{log.userName}</span> - {log.description}</p>
                  <p>{new Date(log.timestamp).toLocaleString()}{log.field ? ` - ${log.field}: ${log.oldValue || "-"} -> ${log.newValue || "-"}` : ""}</p>
                </div>
              ))}
              {!values.activityLogs?.length && <p className="text-sm text-muted-foreground">No activity logged yet.</p>}
            </div>
          </Card>

          <Card className="sticky top-24 w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-3 flex items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">Print preview</h2>
                <p className="text-xs text-muted-foreground">Scaled to fit the screen.</p>
              </div>
              <Button type="button" onClick={print}><Printer size={16} /> Print</Button>
            </div>
            <PrintPreview lesson={printableLesson} zoom={0.34} />
          </Card>
        </aside>
      </div>

      <div aria-hidden className="fixed left-[-12000px] top-0">
        <LessonPrint lesson={printableLesson} ref={printRef} />
      </div>

      <Dialog open={preview} title={`${planType === "daily" ? "Daily" : "Weekly"} Lesson Plan Preview`} onClose={() => setPreview(false)}>
        <div className="mb-4 flex justify-end gap-2">
          <Button onClick={print}><Printer size={17} /> Print</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("pdf")}>{exporting === "pdf" ? <Loader2 className="animate-spin" size={17} /> : <FileDown size={17} />} {exporting === "pdf" ? "PDF..." : "PDF"}</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("docx")}>{exporting === "docx" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />} {exporting === "docx" ? "DOCX..." : "DOCX"}</Button>
        </div>
        <PrintPreview lesson={printableLesson} zoom={0.42} />
      </Dialog>
    </div>
  );
};

const toPrintableLesson = (lesson: LessonPlan): LessonPlan => {
  const subject = lesson.subject || "";
  const gradeClass = lesson.gradeClass || "";
  const chapter = sanitizeChapter(lesson.chapter);
  const support = createAutomaticLessonSupport(subject, gradeClass, chapter);
  const weeklyPlan = normalizeEditableWeeklyPlan(lesson.weeklyPlan, subject, gradeClass, chapter);
  const learningObjectives = hasFilledItems(lesson.learningObjectives)
    ? lesson.learningObjectives
    : support.learningObjectives.map((value, index) => ({ id: `auto-objective-${index + 1}`, value }));
  const learningOutcomes = hasFilledItems(lesson.learningOutcomes)
    ? lesson.learningOutcomes
    : support.learningOutcomes.map((value, index) => ({ id: `auto-outcome-${index + 1}`, value }));
  const successCriteria = hasFilledItems(lesson.successCriteria)
    ? lesson.successCriteria
    : support.successCriteria.map((value, index) => ({ id: `auto-criteria-${index + 1}`, value }));

  return {
    ...lesson,
    schoolName: schoolDisplayName,
    planType: lesson.planType || "weekly",
    subject,
    gradeClass,
    chapter,
    weekStartDate: lesson.weekStartDate || getWeekStartFromDate(lesson.date),
    weekEndDate: lesson.weekEndDate || addBusinessWeekEnd(lesson.weekStartDate || getWeekStartFromDate(lesson.date)),
    topic: buildAutomaticTitle({ ...lesson, subject, gradeClass, chapter, planType: lesson.planType || "weekly" }),
    weeklyPlan: (lesson.planType || "weekly") === "daily" ? weeklyPlan.map((day, index) => (index === 0 ? day : weeklyPlan[index])) : weeklyPlan,
    learningObjectives,
    learningOutcomes,
    successCriteria,
    vocabulary: hasFilledItems(lesson.vocabulary) ? lesson.vocabulary : [{ id: "vocabulary", value: support.vocabulary }],
    materialsResources: hasFilledItems(lesson.materialsResources) ? lesson.materialsResources : [{ id: "materials", value: support.materialsResources }],
    differentiation: mergeFilled({
      strugglingLearners: "",
      eslSupport: "",
      giftedLearners: "",
      specialNeeds: "",
      inclusiveStrategies: support.differentiation
    }, lesson.differentiation || {}),
    assessment: mergeFilled({
      diagnostic: "",
      formative: "",
      summative: "",
      observationChecklist: "",
      rubric: "",
      exitTicket: "",
      teacherComments: support.assessment
    }, lesson.assessment || {}),
    reflection: mergeFilled({
      whatWentWell: "",
      challenges: "",
      improvements: "",
      followUpActivities: "",
      teacherNotes: support.reflection
    }, lesson.reflection || {})
  };
};

const normalizeEditableWeeklyPlan = (weeklyPlan: Partial<WeeklyPlanDay>[] | undefined, subject = "", gradeClass = "", chapter = ""): WeeklyPlanDay[] => {
  const base = createFlexibleWeeklyPlan(subject, gradeClass, chapter);

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: weeklyPlan?.[index]?.lesson ?? day.lesson,
    objectives: weeklyPlan?.[index]?.objectives ?? day.objectives,
    presentation: weeklyPlan?.[index]?.presentation ?? day.presentation,
    guidedPractice: weeklyPlan?.[index]?.guidedPractice ?? day.guidedPractice,
    exitTicket: weeklyPlan?.[index]?.exitTicket ?? day.exitTicket,
    assessment: weeklyPlan?.[index]?.assessment ?? day.assessment,
    homework: weeklyPlan?.[index]?.homework ?? day.homework
  }));
};

const buildAutomaticTitle = (lesson: Partial<LessonPlan>) => {
  const subject = sanitizeTitlePart(lesson.subject);
  const gradeClass = sanitizeTitlePart(lesson.gradeClass);
  const chapter = sanitizeChapter(lesson.chapter);
  const parts = [
    lesson.planType === "daily" ? "Daily Lesson Plan" : "Weekly Lesson Plan",
    subject,
    gradeClass,
    lesson.planType === "daily" ? lesson.date || "" : lesson.week ? `Week ${lesson.week}` : "",
    chapter
  ]
    .map((part) => part?.trim())
    .filter(Boolean);

  return parts.length > 1 ? parts.join(" - ") : "Weekly Lesson Plan";
};

const sanitizeChapter = (value?: string) => {
  const text = value?.trim() || "";
  return text.toLowerCase().startsWith("weekly lesson plan") ? "" : text;
};

const sanitizeTitlePart = (value?: string) => {
  const text = value?.trim() || "";
  return text.toLowerCase().startsWith("weekly lesson plan") ? "" : text;
};

const normalizeSchoolYear = (value?: string) => value?.replace(/\s+/g, "") || "";

const formatWeekRangeLabel = (week?: string, start?: string, end?: string) => {
  const weekLabel = week?.toLowerCase().startsWith("week") ? week : `Week ${week || "1"}`;
  return `${weekLabel} from ${formatDateLabel(start)} to ${formatDateLabel(end)}`;
};

const formatDateLabel = (value?: string) => {
  if (!value) return "...";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return "...";
  return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(date);
};

const getWeekStartFromDate = (value?: string) => {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() - ((date.getDay() + 6) % 7));
  return toIsoDate(date);
};

const addBusinessWeekEnd = (value?: string) => {
  if (!value) return "";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() + 4);
  return toIsoDate(date);
};

const toIsoDate = (date: Date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const createDailyObjective = (lessonTitle = "", subject = "", gradeClass = "") => {
  const lesson = lessonTitle.trim() || "the lesson";
  const subjectLabel = subject.trim() || "the subject";
  const gradeLabel = gradeClass.trim() || "the class";

  return `By the end of the lesson, learners in ${gradeLabel} should be able to explain, practise, and apply ${lesson} in ${subjectLabel}.`;
};

const isGenericObjective = (objective: string, gradeClass = "", chapter = "") => {
  const text = objective.trim();
  if (!text) return true;

  return (
    text.includes("the selected unit") ||
    text.includes("the class") ||
    text === `By the end of the lesson, learners in ${gradeClass || "the class"} should be able to understand and apply the key ideas from ${chapter || "the selected unit"}.`
  );
};

const hasFilledItems = (items?: { value?: string }[]) => Boolean(items?.some((item) => item.value?.trim()));
const unique = (values: string[]) => Array.from(new Set(values.map((value) => value.trim()).filter(Boolean))).sort((a, b) => a.localeCompare(b));

const mergeFilled = <T extends Record<string, string>>(base: T, overrides: Partial<T>): T => {
  const next = { ...base };

  Object.entries(overrides).forEach(([key, value]) => {
    if (typeof value === "string" && value.trim()) {
      next[key as keyof T] = value as T[keyof T];
    }
  });

  return next;
};

const textToItems = (text: string, prefix: string) => {
  const lines = text.split(/\r?\n/).map((value) => value.trim()).filter(Boolean);
  return (lines.length ? lines : [""]).map((value, index) => ({ id: `${prefix}-${index + 1}`, value }));
};

const LockedSchool = () => (
  <div className="space-y-1">
    <Label>School</Label>
    <div className="flex h-10 items-center gap-2 rounded-md border border-border bg-input px-3 text-sm font-bold text-foreground shadow-sm dark:border-cyan-300/20 dark:bg-[#030d14]/85 dark:text-[#f8fdff]">
      <img src={schoolImage} alt="KCS logo" className="h-6 w-6 rounded-sm object-contain bg-white" />
      <span className="truncate">{schoolDisplayName}</span>
    </div>
  </div>
);

const Field = ({ label, children, error }: { label: string; children: React.ReactNode; error?: string }) => (
  <div className="min-w-0 space-y-1">
    <Label>{label}</Label>
    {children}
    {error && <p className="text-xs font-semibold text-destructive">{error}</p>}
  </div>
);

const statusLabel = (status: LessonPlan["status"]) => ({
  draft: "Draft",
  submitted: "Submitted",
  "under-review": "Under Review",
  approved: "Approved",
  rejected: "Rejected",
  archived: "Archived",
  published: "Published"
})[status];

const PrintPreview = ({ lesson, zoom }: { lesson: LessonPlan; zoom: number }) => {
  const pageCount = estimatePrintPageCount(lesson);
  const viewportZoom = typeof window === "undefined" ? zoom : Math.min(zoom, Math.max(0.22, (window.innerWidth - 48) / 1123));
  const width = `${297 * viewportZoom}mm`;
  const height = `${210 * pageCount * viewportZoom}mm`;
  const style = { "--preview-scale": viewportZoom } as CSSProperties;

  return (
    <div className="max-h-[72dvh] max-w-full overflow-auto rounded-lg border border-cyan-300/15 bg-slate-950/70 p-2 sm:p-3">
      <div style={{ width, height }} className="mx-auto">
        <div className="origin-top-left scale-[var(--preview-scale)]" style={style}>
          <LessonPrint lesson={lesson} />
        </div>
      </div>
    </div>
  );
};

const estimatePrintPageCount = (lesson: LessonPlan) => {
  const notesLength = [
    lesson.learningObjectives,
    lesson.learningOutcomes,
    lesson.successCriteria,
    lesson.vocabulary,
    lesson.materialsResources
  ].flatMap((items) => items?.map((item) => item.value) || []).join(" ").length;
  const supportLength = [lesson.referenceBook, ...Object.values(lesson.differentiation || {}), ...Object.values(lesson.assessment || {}), ...Object.values(lesson.reflection || {})].join(" ").length;
  return notesLength + supportLength > 700 ? 2 : 1;
};
