import { forwardRef } from "react";
import { createFlexibleWeeklyPlan, isAutoGeneratedWeeklyPlan, schoolDisplayName, schoolImage } from "../data/defaults";
import { LessonPlan, WeeklyPlanDay } from "../types/lesson";

type RowKey = Exclude<keyof WeeklyPlanDay, "day">;

const pageGroups: { title: string; rows: [RowKey, string][] }[] = [
  {
    title: "Lessons and Objectives",
    rows: [
      ["lesson", "Lesson"],
      ["objectives", "Objectives"]
    ]
  },
  {
    title: "Teaching and Practice",
    rows: [
      ["presentation", "Presentation"],
      ["guidedPractice", "Guided Practice"]
    ]
  },
  {
    title: "Checking Understanding",
    rows: [
      ["exitTicket", "Exit Ticket"],
      ["assessment", "Assessment"],
      ["homework", "Homework"]
    ]
  }
];

export const LessonPrint = forwardRef<HTMLDivElement, { lesson: LessonPlan }>(({ lesson }, ref) => {
  const weeklyPlan = normalizeWeeklyPlan(lesson);

  return (
    <div ref={ref} className="space-y-4 bg-transparent text-black">
      {pageGroups.map((group, pageIndex) => (
        <PrintPage key={group.title} lesson={lesson} pageTitle={group.title} pageNumber={pageIndex + 1}>
          <LessonTable rows={group.rows} weeklyPlan={weeklyPlan} />
          {pageIndex === 2 && <PrintNotes lesson={lesson} />}
        </PrintPage>
      ))}
    </div>
  );
});

LessonPrint.displayName = "LessonPrint";

const PrintPage = ({ lesson, pageTitle, pageNumber, children }: { lesson: LessonPlan; pageTitle: string; pageNumber: number; children: React.ReactNode }) => (
  <section className="print-page mx-auto flex flex-col overflow-hidden bg-white p-[8mm] font-serif text-black shadow-fluent">
    <img src={schoolImage} alt="" className="pointer-events-none absolute left-1/2 top-1/2 h-[390px] w-[390px] -translate-x-1/2 -translate-y-1/2 object-contain opacity-[0.025]" />
    <header className="relative grid grid-cols-[64px_1fr_92px] items-center border-b-2 border-black pb-2">
      <img src={schoolImage} alt="KCS logo" className="h-[54px] w-[54px] object-contain" />
      <div className="text-center">
        <p className="text-[11px] font-bold uppercase tracking-wide">{safeText(lesson.schoolName, schoolDisplayName)}</p>
        <h1 className="text-[17px] font-bold uppercase tracking-wide">Weekly Lesson Plan</h1>
        <p className="text-[10px] font-semibold">{pageTitle}</p>
      </div>
      <div className="text-right text-[9px] leading-tight">
        <p className="font-bold">Page {pageNumber}/3</p>
        <p>Week {safeText(lesson.week, "1")}</p>
        <p>{safeText(lesson.schoolYear, "2026 - 2027")}</p>
      </div>
    </header>

    <div className="relative mt-2 grid grid-cols-4 gap-x-5 gap-y-1 text-[9px] leading-tight">
      <Line label="Subject" value={lesson.subject} />
      <Line label="Grade" value={safeText(lesson.gradeClass).replace(/^Grade\s*/i, "")} />
      <Line label="Quarter" value={lesson.quarter} />
      <Line label="Duration" value={lesson.duration} />
      <Line label="Teacher" value={lesson.teachers} wide />
      <Line label="Chapter" value={lesson.chapter || lesson.topic} wide />
    </div>

    <main className="relative mt-3 min-h-0 flex-1">{children}</main>
  </section>
);

const LessonTable = ({ rows, weeklyPlan }: { rows: [RowKey, string][]; weeklyPlan: WeeklyPlanDay[] }) => (
  <table className="h-full w-full table-fixed border-collapse border border-black text-[8.2px] leading-[1.12]">
    <thead>
      <tr className="h-[9mm]">
        <th className="w-[10.5%] border border-black bg-zinc-100 px-1 text-center font-bold">Day</th>
        {weeklyPlan.map((day) => (
          <th key={day.day} className="border border-black bg-zinc-100 px-1 text-center font-bold">
            {day.day}
          </th>
        ))}
      </tr>
    </thead>
    <tbody>
      {rows.map(([key, label]) => (
        <tr key={key} className="align-top">
          <th className="border border-black bg-zinc-50 px-1 py-1 text-center font-bold">{label}</th>
          {weeklyPlan.map((day) => (
            <td key={`${day.day}-${key}`} className="border border-black p-1 align-top">
              <div className="max-h-[56mm] overflow-hidden whitespace-pre-line break-words">{safeText(day[key])}</div>
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  </table>
);

const PrintNotes = ({ lesson }: { lesson: LessonPlan }) => (
  <div className="mt-3 grid grid-cols-3 gap-2 text-[8.2px] leading-tight">
    <Box title="Key Vocabulary" value={lesson.vocabulary?.map((item) => item.value).filter(Boolean).join("; ")} />
    <Box title="Materials / Resources" value={lesson.materialsResources?.map((item) => item.value).filter(Boolean).join("; ")} />
    <Box title="References" value={lesson.referenceBook} />
    <Box title="Differentiation" value={Object.values(lesson.differentiation || {}).filter(Boolean).join("; ")} />
    <Box title="Assessment Notes" value={Object.values(lesson.assessment || {}).filter(Boolean).join("; ")} />
    <Box title="Reflection" value={Object.values(lesson.reflection || {}).filter(Boolean).join("; ")} />
  </div>
);

const Line = ({ label, value, wide = false }: { label: string; value?: string; wide?: boolean }) => (
  <div className={`flex min-w-0 items-end gap-1 ${wide ? "col-span-2" : ""}`}>
    <span className="shrink-0 font-bold">{label}:</span>
    <span className="min-h-[12px] flex-1 truncate border-b border-black px-1">{safeText(value)}</span>
  </div>
);

const Box = ({ title, value }: { title: string; value?: string }) => (
  <div className="h-[18mm] overflow-hidden border border-black p-1">
    <p className="font-bold">{title}</p>
    <p className="mt-0.5 whitespace-pre-line break-words">{safeText(value)}</p>
  </div>
);

const normalizeWeeklyPlan = (lesson: LessonPlan) => {
  const weeklyPlan = lesson.weeklyPlan;
  const base = createFlexibleWeeklyPlan(lesson.subject, lesson.gradeClass, lesson.chapter || lesson.topic);

  if (isAutoGeneratedWeeklyPlan(weeklyPlan, lesson.subject, lesson.gradeClass, lesson.chapter || lesson.topic)) {
    return base;
  }

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: safeText(weeklyPlan?.[index]?.lesson, day.lesson),
    objectives: safeText(weeklyPlan?.[index]?.objectives, day.objectives),
    presentation: safeText(weeklyPlan?.[index]?.presentation, day.presentation),
    guidedPractice: safeText(weeklyPlan?.[index]?.guidedPractice, day.guidedPractice),
    exitTicket: safeText(weeklyPlan?.[index]?.exitTicket, day.exitTicket),
    assessment: safeText(weeklyPlan?.[index]?.assessment, day.assessment),
    homework: safeText(weeklyPlan?.[index]?.homework, day.homework)
  }));
};

const safeText = (value?: unknown, fallback = " ") => {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim();
  return trimmed || fallback;
};
